version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /experimental/li-cli
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /experimental/license-inventory
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directory: /localgit
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/git-proxy-cli
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /plugins/git-proxy-plugin-samples
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /test/fixtures/test-package
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /website
    schedule:
      interval: weekly
