services:
  git-proxy:
    build:
      context: .
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max

  git-server:
    build:
      context: test/e2e/localgit/
      cache_from:
        - type=gha
      cache_to:
        - type=gha,mode=max
