#!/usr/bin/env bash

# Uncomment to enable debugging
#set -o xtrace

server=http://localhost:8080

#
# Approve commit by ID
#
function authenticate () {
  echo "Auth: $1 $2 "

  http_response=$(curl \
    --header "Content-Type: application/json" \
    --cookie-jar git-proxy-cookie \
    --write-out '%{http_code}' \
    --silent \
    --output curl-response.txt \
    --request POST \
    --data "{\"username\":\"$1\",\"password\":\"$2\"}" \
    "${server}/auth/login")

  if [ "$http_response" != "200" ]; then
      echo "Error: Authenticate: '${http_response}'"
      exit 1
  else
      echo "Authenticate OK"
  fi
}

#
# Approve commit by ID
#
function approve_commit () {
  echo "Approve commit: $1"

  if [ ! -f git-proxy-cookie ]; then
      echo "Error: Authentication required"
      exit 1
  fi

  http_response=$(curl \
    --cookie git-proxy-cookie \
    --write-out '%{http_code}' \
    --silent \
    --output curl-response.txt \
    --request GET \
    "${server}/api/v1/push/${1}")

  if [ "$http_response" != "200" ]; then
      echo "Error: Approve commit: Commit not found: '${http_response}'"
      exit 1
  fi

  http_response=$(curl \
    --cookie git-proxy-cookie \
    --write-out '%{http_code}' \
    --silent \
    --output curl-response.txt \
    --request POST \
    "${server}/api/v1/push/${1}/authorise")

  if [ "$http_response" != "200" ]; then
      echo "Error: Approve commit: '${http_response}'"
      exit 1
  else
      echo "Approve commit OK"
  fi
}

#
# Check for dependencies
#
declare -r dependencies=("curl --help" "jq --help")
for dependency in "${dependencies[@]}"
do
  if ! command -v $dependency &> /dev/null
  then
    echo "Error: ${dependency} could not be found"
    exit 1
  fi
done

#
# Parse command line arguments
#
if [ "$#" -gt 0 ]; then
  case "$1" in
    --auth)
      if [ "$#" -ne 3 ]; then
        echo "Usage: git-proxy-cli --auth <username> <password>"
        exit 11
      fi
      authenticate "$2" "$3"
      ;;
    --approve)
      if [ "$#" -ne 2 ]; then
        echo "Usage: git-proxy-cli --approve <commit-id>"
        exit 12
      fi
      approve_commit "$2"
      ;;
    *)
      echo "Error: unknown command: ${1}"
      exit 2
      ;;
  esac
fi

