services:
  init:
    image: alpine:3.22@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
    init: true
    volumes:
      - mongo-logs:/var/log-mongo
      - tempo-data:/var/tempo
    command: >
      chmod 777 /var/log-mongo && chown -R 10001:10001 /var/tempo

  app:
    container_name: license-inventory
    image: node:23-alpine@sha256:a34e14ef1df25b58258956049ab5a71ea7f0d498e41d0b514f4b8de09af09456
    # ensure colours show
    tty: true
    command: >
      sh -c "npm install --include=optional && npm run dev"
    environment:
      MONGO_URI: mongodb://mongo:27017/inventory
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: license-inventory
      OTEL_RESOURCE_ATTRIBUTES: service.version=0.0.0
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      # have a separate node dependencies
      # avoids permissions conflicts
      - node-deps:/usr/src/app/node_modules
    depends_on:
      - mongo
      - otel-collector

  mongo:
    image: mongo:8.0.15@sha256:ea783d8ac4dcac9f8a7ff236b26a52e36649fc1bdd1778ffb44ba5e4de776cda
    command: --logpath=/var/log/mongo.log
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log
    depends_on:
      - init

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.136.0@sha256:45392d534c1edcc809c2d112394029246bc679d2ae5ea7081414a1fc74f2c621
    volumes:
      - ./dev/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - loki
      - tempo

  promtail:
    image: grafana/promtail:3.5.5@sha256:784743d283f71f644e290d7b9fadf5e1edff405d2756974c6e13fa7978c08b64
    command:
      - -config.file=/etc/promtail/config.yaml
      - -log.level=warn
    volumes:
      - ./dev/promtail.yaml:/etc/promtail/config.yaml
      - mongo-logs:/var/log-mongo
    depends_on:
      - loki

  # traces
  tempo:
    image: grafana/tempo:2.8.2@sha256:0ef775495967cd5d7a6b2e146b6ea695d624803c8db8349fb8ce4164f719f9b7
    command:
      - -config.file=/etc/tempo.yaml
      - -log.level=warn
    volumes:
      - ./dev/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    depends_on:
      - init
      - prometheus

  # metrics
  prometheus:
    image: prom/prometheus:v3.6.0@sha256:76947e7ef22f8a698fc638f706685909be425dbe09bd7a2cd7aca849f79b5f64
    command:
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receive
      - --web.enable-otlp-receiver
      - --log.level=warn
    volumes:
      - ./dev/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090:9090

  # logs
  loki:
    image: grafana/loki:3.5.5@sha256:31628519045e7f28692a7ae73b4a3fd293dccb425585ed5d16ceea3b5c9592e6
    command:
      - -config.file=/etc/loki/loki.yaml
      - -log.level=warn
    ports:
      - 3100:3100
    volumes:
      - ./dev/loki.yaml:/etc/loki/loki.yaml

  # everything dashboard
  grafana:
    image: grafana/grafana:12.2.0@sha256:74144189b38447facf737dfd0f3906e42e0776212bf575dc3334c3609183adf7
    ports:
      - 3001:3000
    volumes:
      - ./dev/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      # seem to get auth warnings even though we're on anonymous auth
      - GF_LOG_LEVEL=error
    depends_on:
      - loki
      - tempo
      - prometheus

volumes:
  mongo-logs:
  mongo-data:
  tempo-data:
  node-deps:
