services:
  init:
    image: alpine:3.22@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1
    init: true
    volumes:
      - mongo-logs:/var/log-mongo
      - tempo-data:/var/tempo
    command: >
      chmod 777 /var/log-mongo && chown -R 10001:10001 /var/tempo

  app:
    container_name: license-inventory
    image: node:23-alpine@sha256:a34e14ef1df25b58258956049ab5a71ea7f0d498e41d0b514f4b8de09af09456
    # ensure colours show
    tty: true
    command: >
      sh -c "npm install --include=optional && npm run dev"
    environment:
      MONGO_URI: mongodb://mongo:27017/inventory
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: license-inventory
      OTEL_RESOURCE_ATTRIBUTES: service.version=0.0.0
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      # have a separate node dependencies
      # avoids permissions conflicts
      - node-deps:/usr/src/app/node_modules
    depends_on:
      - mongo
      - otel-collector

  mongo:
    image: mongo:8.0.12@sha256:a6bda40d00e56682aeaa1bfc88e024b7dd755782c575c02760104fe02010f94f
    command: --logpath=/var/log/mongo.log
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log
    depends_on:
      - init

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.130.1@sha256:9c247564e65ca19f97d891cca19a1a8d291ce631b890885b44e3503c5fdb3895
    volumes:
      - ./dev/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - loki
      - tempo

  promtail:
    image: grafana/promtail:3.5.3@sha256:698c3357886c886bb9a862da36062e130c20bf359d956148e67ee36141ef6f17
    command:
      - -config.file=/etc/promtail/config.yaml
      - -log.level=warn
    volumes:
      - ./dev/promtail.yaml:/etc/promtail/config.yaml
      - mongo-logs:/var/log-mongo
    depends_on:
      - loki

  # traces
  tempo:
    image: grafana/tempo:2.8.1@sha256:bc9245fe3da4e63dc4c6862d9c2dad9bcd8be13d0ba4f7705fa6acda4c904d0e
    command:
      - -config.file=/etc/tempo.yaml
      - -log.level=warn
    volumes:
      - ./dev/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    depends_on:
      - init
      - prometheus

  # metrics
  prometheus:
    image: prom/prometheus:v3.5.0@sha256:63805ebb8d2b3920190daf1cb14a60871b16fd38bed42b857a3182bc621f4996
    command:
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receive
      - --web.enable-otlp-receiver
      - --log.level=warn
    volumes:
      - ./dev/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090:9090

  # logs
  loki:
    image: grafana/loki:3.5.3@sha256:3165cecce301ce5b9b6e3530284b080934a05cd5cafac3d3d82edcb887b45ecd
    command:
      - -config.file=/etc/loki/loki.yaml
      - -log.level=warn
    ports:
      - 3100:3100
    volumes:
      - ./dev/loki.yaml:/etc/loki/loki.yaml

  # everything dashboard
  grafana:
    image: grafana/grafana:12.1.0@sha256:6ac590e7cabc2fbe8d7b8fc1ce9c9f0582177b334e0df9c927ebd9670469440f
    ports:
      - 3001:3000
    volumes:
      - ./dev/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      # seem to get auth warnings even though we're on anonymous auth
      - GF_LOG_LEVEL=error
    depends_on:
      - loki
      - tempo
      - prometheus

volumes:
  mongo-logs:
  mongo-data:
  tempo-data:
  node-deps:
