services:
  init:
    image: alpine:3.21@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099
    init: true
    volumes:
      - mongo-logs:/var/log-mongo
      - tempo-data:/var/tempo
    command: >
      chmod 777 /var/log-mongo && chown -R 10001:10001 /var/tempo

  app:
    container_name: license-inventory
    image: node:23-alpine@sha256:70eca392e3d52cb7d133b52d52e8600d8c410a5eaee6105c11324b28868f9ac9
    # ensure colours show
    tty: true
    command: >
      sh -c "npm install --include=optional && npm run dev"
    environment:
      MONGO_URI: mongodb://mongo:27017/inventory
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: license-inventory
      OTEL_RESOURCE_ATTRIBUTES: service.version=0.0.0
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      # have a separate node dependencies
      # avoids permissions conflicts
      - node-deps:/usr/src/app/node_modules
    depends_on:
      - mongo
      - otel-collector

  mongo:
    image: mongo:8.0.4@sha256:b5725ac74a0d00d2bb48af997535f4eb4e87df61a2054306ae06f258b6c6b337
    command: --logpath=/var/log/mongo.log
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - mongo-logs:/var/log
    depends_on:
      - init

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.119.0@sha256:36c35cc213c0f3b64d6e8a3e844dc90822f00725e0e518eaed5b08bcc2231e72
    volumes:
      - ./dev/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - loki
      - tempo

  promtail:
    image: grafana/promtail:3.4.0@sha256:5a9c3491f52675913905b466c966eaee26bb40c3a4d5ff0aee848f4834ac1997
    command:
      - -config.file=/etc/promtail/config.yaml
      - -log.level=warn
    volumes:
      - ./dev/promtail.yaml:/etc/promtail/config.yaml
      - mongo-logs:/var/log-mongo
    depends_on:
      - loki

  # traces
  tempo:
    image: grafana/tempo:2.7.0@sha256:12e904cc509a8e0bd87815e0bc719b6167933bc3f2532716a85811af967780f6
    command:
      - -config.file=/etc/tempo.yaml
      - -log.level=warn
    volumes:
      - ./dev/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    depends_on:
      - init
      - prometheus

  # metrics
  prometheus:
    image: prom/prometheus:v3.1.0@sha256:6559acbd5d770b15bb3c954629ce190ac3cbbdb2b7f1c30f0385c4e05104e218
    command:
      - --config.file=/etc/prometheus.yaml
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receive
      - --web.enable-otlp-receiver
      - --log.level=warn
    volumes:
      - ./dev/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - 9090:9090

  # logs
  loki:
    image: grafana/loki:3.4.0@sha256:74b8ccbd6e4b4932874742cf3997389592389ea721b3f210aad266486b985a4c
    command:
      - -config.file=/etc/loki/loki.yaml
      - -log.level=warn
    ports:
      - 3100:3100
    volumes:
      - ./dev/loki.yaml:/etc/loki/loki.yaml

  # everything dashboard
  grafana:
    image: grafana/grafana:11.5.1@sha256:5781759b3d27734d4d548fcbaf60b1180dbf4290e708f01f292faa6ae764c5e6
    ports:
      - 3001:3000
    volumes:
      - ./dev/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor metricsSummary
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      # seem to get auth warnings even though we're on anonymous auth
      - GF_LOG_LEVEL=error
    depends_on:
      - loki
      - tempo
      - prometheus

volumes:
  mongo-logs:
  mongo-data:
  tempo-data:
  node-deps:
