import * as fs from 'fs';
import * as path from 'path';

const banner = '// THIS FILE IS AUTOMATICALLY GENERATED – DO NOT EDIT MANUALLY.\n\n';

const filePath = process.argv[2];

if (!filePath) {
  console.error('Error: Provide a file path as an argument.');
  process.exit(1);
}

const resolvedPath = path.resolve(filePath);

if (!fs.existsSync(resolvedPath)) {
  console.error(`Error: The file "${resolvedPath}" does not exist.`);
  process.exit(1);
}

const originalContent = fs.readFileSync(resolvedPath, 'utf8');

if (!originalContent.startsWith(banner)) {
  fs.writeFileSync(resolvedPath, banner + originalContent, 'utf8');
}
