---
name: Add PR Labels

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  auto_label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@34d80673e067bdc0c24568d3af899c216adcfaa9
        with:
          config-name: release-drafter-config.yml
