---
name: Add PR Labels

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: read

jobs:
  auto_label:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter/autolabeler@72967cdc98ddd3160f1fc3dff619de365e137dd0
        with:
          config-name: release-drafter-config.yml
