name: experimental-inventory-cli - Publish to NPM
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version without v prefix'
        required: true
        type: string
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: check version matches input
        run: |
          grep "\"version\": \"${{ github.event.inputs.version }}\"," package.json
        working-directory: ./experimental/li-cli

      - run: npm ci
        working-directory: ./experimental/li-cli

      - run: npm run build
        working-directory: ./experimental/li-cli

      - run: npm publish --access=public
        working-directory: ./experimental/li-cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
