name: experimental-inventory - Publish to NPM
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'release version without v prefix'
        required: true
        type: string
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: check version matches input
        run: |
          grep "\"version\": \"${{ github.event.inputs.version }}\"," package.json
        working-directory: ./experimental/license-inventory

      - run: npm ci
        working-directory: ./experimental/license-inventory

      - run: npm run build
        working-directory: ./experimental/license-inventory

      - run: npm publish --access=public
        working-directory: ./experimental/license-inventory
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
