name: CI - experimental - inventory

on:
  push:
    branches: [main]
    paths:
      - experimental/license-inventory/**
  pull_request:
    branches: [main]
    paths:
      - experimental/license-inventory/**

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        mongodb-version: [4.4]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@315db7fe45ac2880b7758f1933e6e5d59afd5e94 # 1.12.1
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        working-directory: ./experimental/license-inventory
        run: npm ci

      - name: Test
        working-directory: ./experimental/license-inventory
        run: |
          MONGO_URI="mongodb://localhost:27017/inventory" npm run test
