# This workflow builds the package and checks that the build is correct
# (includes the UI files)

name: Package Smoke Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  smoke-test-package:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Use Node.js 24.x
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x

      - name: Install dependencies
        run: npm ci --no-fund

      - name: Build
        run: npm run build

      - name: Smoke test build
        run: bash ./scripts/package-smoke-test.sh --no-clean-build
