name: Publish samples to NPM

on:
  push:
    tags:
      - 'sample-*'

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: plugins/git-proxy-plugin-samples
        run: npm ci

      - name: Build TypeScript
        working-directory: plugins/git-proxy-plugin-samples
        run: npm run build

      - name: Install peers and publish
        working-directory: plugins/git-proxy-plugin-samples
        run: |
          npm install --include=peer
          npm publish --provenance --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
