name: Publish samples to NPM

on:
  push:
    tags:
      # False positive: setup-node step doesn't use cache input
      # zizmor: ignore[cache-poisoning]
      - 'sample-*'

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: plugins/git-proxy-plugin-samples
        run: npm ci

      - name: Build TypeScript
        working-directory: plugins/git-proxy-plugin-samples
        run: npm run build

      - name: Publish git-proxy-plugin-samples
        working-directory: plugins/git-proxy-plugin-samples
        run: npm publish --provenance --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
