name: Publish samples to NPM

on:
  push:
    tags:
      - 'sample-*'

permissions:
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        working-directory: plugins/git-proxy-plugin-samples
        run: npm ci

      - name: Build TypeScript
        working-directory: plugins/git-proxy-plugin-samples
        run: npm run build

      - name: Publish git-proxy-plugin-samples
        working-directory: plugins/git-proxy-plugin-samples
        run: npm publish --provenance --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
