exports.parsePush = require('./parsePush').exec;
exports.checkRepoInAuthorisedList = require('./checkRepoInAuthorisedList').exec;
exports.audit = require('./audit').exec;
exports.pullRemote = require('./pullRemote').exec;
exports.writePack = require('./writePack').exec;
exports.getDiff = require('./getDiff').exec;
exports.scanDiff = require('./scanDiff').exec;
exports.blockForAuth = require('./blockForAuth').exec;
exports.checkIfWaitingAuth = require('./checkIfWaitingAuth').exec;
exports.checkCommitMessages = require('./checkCommitMessages').exec;
console.log(__dirname);
exports.checkAuthorEmails = require('./checkAuthorEmails').exec;
exports.checkUserPushPermission = require('./checkUserPushPermission').exec;
exports.clearBareClone = require('./clearBareClone').exec;
exports.checkSensitiveData = require('./checkSensitiveData').exec;
exports.checkExifJpeg = require('./checkExifJpeg').exec;
exports.checkForAiMlusage = require('./checkForAiMlUsage').exec;
